-

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -24,26 +24,38 @@
     fi
   }
 
+  COMPILE=false
+  OUT="${SOURCE%.*}.o"
+
   process(){
     local REGEX='^ *# *include +"([^/].*)" *$'
-    my_grep -E "$REGEX" "$1" | sed -E "s~$REGEX~\\1~" | while read -r NON_LOCAL_INCLUDE; do
-      {
-        local INCLUDE="$NON_LOCAL_INCLUDE"
-        if printf '%s\n' "$1" | grep -q /; then
-          local FULL="${1%/*}/$INCLUDE"
-        else
-          local FULL="$INCLUDE"
+    NON_LOCAL_HEADERS="$(my_grep -E "$REGEX" "$1" | sed -E "s~$REGEX~\\1~" | my_grep -vE ' ')"
+    local HEADERS="$NON_LOCAL_HEADERS"
+    for NON_LOCAL_INCLUDE in $HEADERS; do
+      local INCLUDE="$NON_LOCAL_INCLUDE"
+      if printf '%s\n' "$1" | grep -q /; then
+        local FULL="${1%/*}/$INCLUDE"
+      else
+        local FULL="$INCLUDE"
+      fi
+      make "$FULL"
+      if ! [ -f "$FULL" ]; then
+        echo "${0##*/}: $FULL: not found, make didn't create it" >&2
+        exit 1
+      fi
+      if [ -f "$OUT" ]; then
+        if [ "$FULL" -nt "$OUT" ]; then
+          COMPILE=true
         fi
-        make "$FULL"
-        process "$FULL"
-        :
-      } < /dev/null
-      :
+      else
+        COMPILE=true
+      fi
+      process "$FULL"
     done
     :
   }
 
   process "$SOURCE"
-  "$@" -c "$SOURCE"
+  "$COMPILE" && "$@" -c "$SOURCE"
   exit 0
 }
